dumbo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from dumbo import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^$', views.index, name="homepage"),
    
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/register/$', views.register, name='register'),
    url(r'^accounts/logout/$', auth_views.logout, {'next_page':'/'}, name='logout'),

    url(r'^user/my_projects/$', views.my_projects, name="my_projects"),
    url(r'^collab/remove/$', views.delete_collab, name="delete_collab"),
    url(r'^project/collab/(?P<slug>[\w-]*)/$', views.manage_collab, name="manage_collab"),
    url(r'^user/profile/$', views.profile, name="profile"),

    url(r'^project/create/$', views.create_project, name="create_project"),
    url(r'^project/edit/(?P<slug>[\w-]*)/$', views.edit_project, name="edit_project"),
    url(r'^project/view/(?P<slug>[\w-]*)/$', views.view_project, name="view_project"),
    url(r'^project/delete/(?P<slug>[\w-]*)/$', views.delete_project, name="delete_project"),

    url(r'^issue/create/(?P<slug>[\w-]*)/$', views.create_issue, name="create_issue"),
    url(r'^issue/view/(?P<issue_id>[0-9]*)/$', views.view_issue, name="view_issue"),
    url(r'^issue/edit/(?P<issue_id>[0-9]*)/$', views.edit_issue, name="edit_issue"),
    url(r'^issue/upload_file/(?P<issue_id>[0-9]*)/$', views.upload_file, name="upload_file"),
    url(r'^issue/create_comment/(?P<issue_id>[0-9]*)/$', views.create_comment, name="create_comment"),
]

issuetracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('dumbo.urls', namespace = 'dumbo')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dumbo/models.py
from __future__ import unicode_literals

from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User, Group, Permission
from django.utils import timezone
from django.template.defaultfilters import slugify
from django import forms

UNCONFIRMED = "UNCONFIRMED"
CONFIRMED = "CONFIRMED"
PATCH = "PATCH"
CLOSED = "CLOSED"

ISSUE_STATUS = [
    (UNCONFIRMED, UNCONFIRMED),
    (CONFIRMED, CONFIRMED),
    (PATCH, PATCH),
    (CLOSED, CLOSED),
]

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    profile_pic = models.ImageField("Profile Picture", blank = True, null = True, upload_to = "profile_picture/")
    about = models.TextField("About yourself", blank = True)
    private = models.BooleanField("Keep my Profile private", default = False)

class Project(models.Model):
    name = models.CharField("Project Name", max_length = 20)
    slug = models.SlugField(blank = True, unique = True)
    link = models.URLField(blank = True)
    details = models.TextField("About your project")
    owner = models.ForeignKey(User, on_delete = models.CASCADE)
    group = models.ForeignKey(Group, on_delete = models.CASCADE)
    private = models.BooleanField("Is this a private project?", default=False)

    def __unicode__(self):
        return "%s : %s" %(self.name, self.details)

    def save(self, *args, **kwargs):
        if self.slug == self.owner.username:
            ps = slugify(self.name)
            self.slug = ps
            counter = 1
            while Project.objects.filter(slug=self.slug).exists():
                self.slug = ps+str(counter)
                counter += 1
            self.group, c = Group.objects.get_or_create(name=self.slug)
            self.group.user_set.add(self.owner)
        super(Project, self).save(*args, **kwargs)

class Issue(models.Model):
    title = models.CharField("Title", max_length = 20)
    project = models.ForeignKey(Project, on_delete = models.CASCADE)
    content = models.TextField("Whats the issue?")
    tag = models.CharField("Add a tag to the issue", max_length=11, choices=ISSUE_STATUS, default=UNCONFIRMED)
    author = models.ForeignKey(User, on_delete = models.SET_DEFAULT, default = None, related_name='author')
    timestamp = models.DateTimeField(default = timezone.now)
    last_updated = models.DateTimeField(default = timezone.now)
    assignee = models.ForeignKey(User, on_delete = models.SET_DEFAULT, default = None, blank = True, related_name='assignee', null = True)

    def __unicode__(self):
        return "%s : %s" %(self.id, self.title)  

class Attachment(models.Model):
    attachment = models.FileField(upload_to = "attachment/", blank = True)
    issue = models.ForeignKey(Issue, on_delete = models.CASCADE)
    user = models.ForeignKey(User)
    timestamp = models.DateTimeField(default = timezone.now)

class Comment(models.Model):
    comment = models.TextField()
    issue = models.ForeignKey(Issue)
    author = models.ForeignKey(User)
    timestamp = models.DateTimeField(default = timezone.now)

class ProjectForm(ModelForm):
    slug = forms.SlugField(widget=forms.HiddenInput())
    class Meta:
        model = Project
        exclude = []

class UserForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['profile_pic', 'about', 'private']

class IssueForm(ModelForm):
    attachment = forms.FileField()

    class Meta:
        model = Issue
        exclude = []
        widgets = {
            'project':forms.HiddenInput(),
            'author':forms.HiddenInput(),
            'timestamp':forms.HiddenInput(),
            'last_updated':forms.HiddenInput(),
        }

dumbo/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.forms.widgets import HiddenInput
from django.contrib.auth.models import User, Group, Permission
from django.utils import timezone
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import UserForm, ProfileForm, Profile, Project, ProjectForm, Issue, IssueForm, Attachment, Comment
from datetime import datetime

def index(request):
    new_projects = Project.objects.filter(private=False)
    return render(request, "index.html", {'new_projects':new_projects})

def register(request):
    if request.POST:
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST, request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user_form.cleaned_data['password'])
            user.save()
            print user.password
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            return HttpResponseRedirect('/')
    else:
        user_form = UserForm()
        profile_form = ProfileForm()
    return render(request, 'registration/register.html', {'user':user_form, 'profile':profile_form})

@login_required
def create_project(request):
    if request.POST:
        form = ProjectForm(request.POST)
        if form.is_valid():
            form.cleaned_data['owner'] = request.user
            project = form.save()
            return HttpResponseRedirect('/project/view/%s' %(project.slug))
    else:
        g = Group.objects.get_or_create(name=request.user.username)
        form = ProjectForm(initial={'owner':request.user, 'slug':request.user, 'group':g})
        form.fields['owner'].widget = HiddenInput()
        form.fields['group'].widget = HiddenInput()
    return render(request, "form_template.html", {'form':form})

def view_project(request, slug):
    project = get_object_or_404(Project, slug=slug)
    if project.private is True and request.user not in project.group.user_set.all():
        return Http404("Page not Found")
    issues = Issue.objects.filter(project=project)
    return render(request, "view_project.html", {'project':project, 'issues':issues})

@login_required
def edit_project(request, slug):
    project = get_object_or_404(Project, slug=slug)
    if project.private is True and request.user not in project.group.user_set.all():
        return Http404("Page not Found")
    if request.method == "POST":
        form = ProjectForm(request.POST, instance = project)
        form.fields['owner'].widget = HiddenInput()
        if form.is_valid():
            form.cleaned_data['owner'] = request.user
            project.save()
            return HttpResponseRedirect('/project/view/%s' %(project.slug))        
    else:
        form = ProjectForm(instance = project)
        form.fields['owner'].widget = HiddenInput()
    return render(request, "form_template.html", {'form':form})

@login_required
def delete_project(request, slug):
    get_object_or_404(Project, slug=slug, owner=request.user).delete()
    return HttpResponseRedirect("/")

@login_required
def my_projects(request):
    projects = Project.objects.filter(owner=request.user)
    return render(request, "my_projects.html", {"projects":projects})

@login_required
def manage_collab(request, slug):
    project = get_object_or_404(Project, slug=slug, owner=request.user)
    if request.method == "POST":
        username = request.POST.get("username")
        user = User.objects.get(username=username)
        project.group.user_set.add(user)
    collab_list = project.group.user_set.all()
    return render(request, "collab.html", {"project":project, "collab_list":collab_list})

@login_required
def delete_collab(request):
    if request.method == "POST":
        slug = request.POST.get("project")
        project = get_object_or_404(Project, slug=slug, owner=request.user)
        user = User.objects.get(username=request.POST.get("username"))
        project.group.user_set.remove(user)
        return HttpResponseRedirect("/project/collab/%s" %(project.slug))
    return Http404("No")

@login_required
def create_issue(request, slug):
    project = get_object_or_404(Project, slug=slug, owner=request.user)
    if project.private is True and request.user not in project.group.user_set.all():
        return Http404("Page not Found")
    if request.method == "POST":
        form = IssueForm(request.POST, request.FILES)
        if form.is_valid():
            issue = form.save(commit=False)
            issue.user = request.user
            issue.tag = "UNCONFIRMED"
            issue.project = project
            issue.save()
            if request.FILES:
                attachment = Attachment(attachment=request.FILES['attachment'], issue = issue, user=request.user)
                attachment.save()
            return HttpResponseRedirect("/project/view/%s" %(project.slug))
    else:
        form = IssueForm(initial={'tag':'UNCONFIRMED', 'author':request.user, 'project':project})
    return render(request, "form_template.html", {"form":form})

@login_required
def create_comment(request, issue_id):
    if request.method =="POST":
        issue = get_object_or_404(Issue, id=issue_id)
        comment = Comment(issue=issue, author=request.user, comment=request.POST['comment'])
        comment.save()
        return HttpResponseRedirect("/issue/view/%s" %(issue_id))
    return Http404("No")

@login_required
def upload_file(request, issue_id):
    issue = get_object_or_404(Issue, id=issue_id)
    if request.method =="POST":
        attachment = Attachment(attachment=request.FILES['attachment'], issue = issue, user=request.user)
        attachment.save()
        return HttpResponseRedirect("/issue/view/%s" %(issue_id))
    return Http404("No")

def view_issue(request, issue_id):
    issue = get_object_or_404(Issue, id=issue_id)
    comments = Comment.objects.filter(issue=issue)
    attachments = Attachment.objects.filter(issue=issue)
    project = issue.project
    if project.private is True and request.user not in project.group.user_set.all():
        return Http404("Page not Found")
    return render(request, "view_issue.html", {"issue":issue, "attachments":attachments, "comments":comments})

@login_required
def edit_issue(request, issue_id):
    issue = get_object_or_404(Issue, id=issue_id)
    project = issue.project
    if request.method == "POST":
        form = IssueForm(request.POST, request.FILES)
        if form.is_valid():
            issue = form.save(commit=False)
            issue.user = request.user
            issue.project = project
            issue.save()
            return HttpResponseRedirect("/project/view/%s" %(project.slug))
    else:
        form = IssueForm(instance=issue)
    form.fields['attachment'].widget = HiddenInput()
    return render(request, "form_template.html", {'issue':issue, 'project':project, 'form':form})

@login_required
def profile(request):
    profile = get_object_or_404(Profile, user=request.user)
    projects = Project.objects.filter(owner=request.user)
    return render(request, "profile.html", {"profile":profile, "projects":projects})

dumbo/templates/collab.html
{% extends 'layout.html' %}
{% block main_content %}
<h3>Collaborators for {{project.name}}</h3>
<h4>Add User</h4>
<form action="" method="POST">
  {% csrf_token %}
  <label for="user">
	Username:
  </label>
  <input name="username" type="text" style="width:200px">
  <input type="submit" value="Add" />
</form>

<h4>Current Collabs</h4>
<ul>
  {% for c in collab_list %}
  <li>{{c.username}}
	{% if user != c %}<form method="POST" action={% url "dumbo:delete_collab" %} style="display:inline">
	  {% csrf_token %}
	  <input type="hidden" value={{project.slug}} name="project" />
	  <input type="hidden" value={{c.username}} name="username" />
	  <input type="submit" value="Remove" />	  
	</form></li>{% endif %}
  {% empty %}
  You have no collaborators. Add some!
  {% endfor %}
</ul>
{% endblock %}

dumbo/templates/form_template.html
{% extends 'layout.html' %}
{% block main_content %}

{{form.errors}}
<form action="." method="POST" style="width:70%; padding-bottom:10%;" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Submit" />
</form>
{% endblock %}

dumbo/templates/index.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block page_title %} Dumbo {% endblock %}
{% block page_heading %} Dumbo <p /> The Simple Issue Tracker {% endblock %}

{% block right_bar %}
<h4>Discover new projects!</h4>
{% for i in new_projects %}
<a href={% url "dumbo:view_project" i.slug %}>{{i.name}}</a><br />
{% endfor %}
{% endblock %}

{% block main_content %}
{% if user.is_authenticated %}
<h2>Your notifications</h2>
{% else %}
Discover Dumbo Today!<p>
Lots of features
{% endif %}
{% endblock %}

dumbo/templates/layout.html
<!doctype html>
<html class="no-js" lang="en">
  <head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<title>{% block page_title %} Dumbo - The simple issue tracker {% endblock %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" href={% static 'index.css' %}>
  </head>
  <body>
	
	<div class="top-bar">
	  <div class="top-bar-left">
		<ul class="menu">
		  <a href={% url "dumbo:homepage" %}>
			<li class="menu-text">{% block company_name %}Dumbo - Keep It Simple Stupid{% endblock %}</li>
		  </a>
		</ul>
	  </div>
	  <div class="top-bar-right">
		<ul class="menu">
		  {% if user.is_authenticated %}
		  <li><a href={% url "dumbo:create_project" %}>Create a Project</a></li>
		  <li><a href={% url "dumbo:my_projects" %}>My Projects</a></li>
		  <li><a href={% url "dumbo:profile" %}>Profile</a></li>
		  <li><a href={% url "dumbo:logout" %}>Logout</a></li>
		  {% else %}
		  <li><a href={% url "dumbo:login" %}>Login</a></li>
		  <li><a href={% url "dumbo:register" %}>Register</a></li>
		  {% endif %}
		</ul>
	  </div>
	</div>
	
	<div class="callout large primary">
	  <div class="row column text-center">
		<h1>{% block page_heading%} DUMBO {% endblock %}</h1>
	  </div>
	</div>
	<div class="row" id="content">
	  <div class="medium-8 columns">
		{% block main_content %}
		<div class="blog-post">
		  <h3>Awesome blog post title <small>3/6/2015</small></h3>
		  <img class="thumbnail" src="http://placehold.it/850x350">
		  <p>Praesent id metus massa, ut blandit odio. Proin quis tortor orci. Etiam at risus et justo dignissim congue. Donec congue lacinia dui, a porttitor lectus condimentum laoreet. Nunc eu ullamcorper orci. Quisque eget odio ac lectus vestibulum faucibus eget in metus. In pellentesque faucibus vestibulum. Nulla at nulla justo, eget luctus.</p>
		  <div class="callout">
			<ul class="menu simple">
			  <li><a href="#">Author: Mike Mikers</a></li>
			  <li><a href="#">Comments: 3</a></li>
			</ul>
		  </div>
		</div>
		{% endblock %}
	  </div>
	  
	  <div class="medium-3 columns" data-sticky-container>
		<div class="sticky" data-sticky data-anchor="content">
		  {% block right_bar %}
		  {% endblock %}
		</div>
	  </div>
	</div>
	<!--
	<div class="row column">
	  <ul class="pagination" role="navigation" aria-label="Pagination">
		<li class="disabled">Previous</li>
		<li class="current"><span class="show-for-sr">You're on page</span> 1</li>
		<li><a href="#" aria-label="Page 2">2</a></li>
		<li><a href="#" aria-label="Page 3">3</a></li>
		<li><a href="#" aria-label="Page 4">4</a></li>
		<li class="ellipsis"></li>
		<li><a href="#" aria-label="Page 12">12</a></li>
		<li><a href="#" aria-label="Page 13">13</a></li>
		<li><a href="#" aria-label="Next page">Next</a></li>
	  </ul>
	</div>
	-->
	<!--script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
	<script src="http://dhbhdrzi4tiry.cloudfront.net/cdn/sites/foundation.js"></script>
	<script>
      $(document).foundation();
    </script-->
  </body>
</html>

dumbo/templates/my_projects.html
{% extends 'layout.html' %}
{% block main_content %}
<title>Hello</title>
{% if not projects %}

{% endif %}
{% for project in projects %}
<h3>{{project.name}}</h3>
<div><a href={% url "dumbo:manage_collab" project.slug %}>
  Manage collabarators
</a></div>
<a href={% url "dumbo:edit_project" project.slug %}>Edit</a> |
<a href={% url "dumbo:view_project" project.slug %}>View</a> |
<a href={% url "dumbo:delete_project" project.slug %}>Delete</a> <p />
About:
{{project.details}}
<hr />
{% empty %}
<h3>You have no projects currently</h3>
{% endfor %}
{% endblock %}

dumbo/templates/profile.html
{% extends 'layout.html' %}

{% block main_content %}

<h4>Profile</h4>
{% if profile.private == True and profile.user != user %}
The user has set his profile to private
{% else %}
{% if profile.profile_pic %}
{{ profile.profile_pic}}
{% endif %}
<h5>{{user}}</h5>
Joined : {{user.date_joined}}
<p />
Last Login : {{user.last_login}}
<p />
  About: {{profile.about}}
<p />
<h4>Current Projects:</h4>
<p />
{% for p in projects %}
<b>{{p.project_name}}</b> : {{p.details}}<p />
{% endfor %}
<p />
{% endif %}
{% endblock %}

dumbo/templates/view_issue.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block main_content %}
<h3>#{{issue.id}} {{issue.title}}<p /></h3>
{% if user in issue.project.group.user_set.all %}
<p><a href={% url "dumbo:edit_issue" issue.id %}>Edit Issue</a></p>
{% endif %}
{{issue.tag}}<br />
{{issue.timestamp}} by {{issue.author}} <br>
Last updated at: {{issue.last_updated}}
<br>
Assigned to: {{issue.assignee}}

<p>{{issue.content}}</p>

<p /> <hr>

  {% if attachments %}
  {% for a in attachments %}
<div style="background:silver">
  <a href='{{a.attachment.url}}'>{{a.attachment.name}}</a> {{a.user}} {{a.timestamp}}
  {% if not forloop.last %}
  <br />
  {% endif %}
</div>
  {% endfor %}
  {% endif %}
<hr>
<h4>Add an attachment</h4>
<form action={% url "dumbo:upload_file" issue.id %} method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="file" name="attachment" />
  <input type="submit" value="Submit" />
</form>

<hr />
<h3>Comments</h3>
{% for c in comments %}
{{c.comment}}  {{c.author}} {{c.timestamp}}<br />
{% empty %}
<h5>No Comments!</h5>
{% endfor %}
<hr />
Create a comment
<form action={% url "dumbo:create_comment" issue.id %} method="POST">
  {% csrf_token %}
  <input type="text" name="comment" />
  <input type="submit" value="Comment" />
</form>
{% endblock %}

dumbo/templates/view_project.html
{% extends 'layout.html' %}
{% load staticfiles %}

{% block main_content %}
<h3>{{project.name}}</h3>
{% if project.owner == user %}
<a href={% url 'dumbo:edit_project' project.slug %}>Edit Project</a> |
<a href={% url 'dumbo:delete_project' project.slug %}>Delete Project <p/></a>
{% else %}
Owner: {{project.owner}} <p />
{% endif %}
<a href={% url 'dumbo:create_issue' project.slug %}><h6>Create an Issue</h6></a>
<p />
<a href={{project.link}}>Project Website</a><p />
{{project.details}}<p />
<br />
<hr>
<h3>Issues</h3>
{% for i in issues %}
<div style="background:silver">

  <a href={% url "dumbo:view_issue" i.id %}> {{ i.title }} : {{i.content}}<br /></a>
  Status:{{i.tag}}<br>
  Created on:{{i.timestamp}} Last Updated:{{i.last_updated}}<br />

</div>
<br>
{% empty %}
No issues
{% endfor %}

{% endblock %}